--- # OpenNMS Configuration Module 
config_module_info:
  author: The author of the module, e.g. Ronny Trommer <ronny@opennms.org>
  description: This is a short nice written description what your configuration module is about
  company: An optional field if you want to expose the company you work for, otherwise leave empty
  license: This is a required field and sets the License, e.g. Apache License 2.0, AGPLv3+, GPLv2, BSD, MIT or WTFPL
  categories:
    - linux
    - webserver
    - apache2
