= Monitoring Apache2 with OpenNMS

== Required

- Apache2 webserver is configured with mod_status and can be accessed through localhost.
- Net-SNMP agent is installed and configured.
- Python with library `python-urlgrabber` is installed

== Setup Net-SNMP agent

.Create workspace directory and download the scripts and configuration files
[source,bash]
----
mkdir ${HOME}/opennms-config-workspace
cd ${HOME}/opennms-config-workspace
git clone https://github.com/opennms-config-modules/apache.git
----

.Install Net-SNMP extend script
[source,bash]
----
mkdir /etc/snmp/extend
cp ${HOME}/opennms-config-workspace/apache/assets/apache-stats.py /etc/snmp/extend
chmod +x /etc/snmp/extend/apache-stats.py
----

Create directory for caching

[source,bash]
----
mkdir -p /var/local/snmp/cache/apache
chown snmp:snmp /var/local/snmp/cache/apache
----

Extend Net-SNMP agent with 'apache-stats.py' in `snmpd.conf`

[source,bash]
----
extend apache /etc/snmp/extend/apache-stats.py
----

Test output with

[source,bash]
----
snmpwalk -On -v2c -c ${community} ${host} .1.3.6.1.4.1.8072.1.3.2.4.1.2.6.97.112.97.99.104.101
----

== Setup OpenNMS monitoring

Drop in data collection config and RRD graph definitions:

[source.bash]
----
cp ${HOME}/opennms-config-workspace/apache/datacollection/*.xml ${OPENNMS_HOME}/etc/datacollection
cp ${HOME}/opennms-config-workspace/apache/snmp-graph.properties.d/*.properties ${OPENNMS_HOME}/etc/snmp-graph.properties.d
----

Include data collection for Net-SNMP server

[source, bash]
----
vi ${OPENNMS_HOME}/etc/datacollection-config.xml

#Add include here
<include-collection dataCollectionGroup="apache2"/>

# restart OpenNMS
systemctl restart opennms
----

== Install Syslog parser

Drop the Syslog parsing rule definition:

[source.bash]
----
cp ${HOME}/opennms-config-workspace/apache/syslog/*.syslog.xml ${OPENNMS_HOME}/etc/syslog
----

== Credits

With thanks to Glen Pitt-Pladdy for the heavy lifting in `apache-stats.py`.
